export const data = {
  id: 4673,
  name: "POCO X3 Pro",
  slug: "poco-x3-pro",
  permalink: "https://www.tugangastores.com/producto/poco-x3-pro/",
  date_created: "2021-06-04T19:43:05",
  date_created_gmt: "2021-06-05T00:43:05",
  date_modified: "2022-04-12T11:58:32",
  date_modified_gmt: "2022-04-12T16:58:32",
  type: "variable",
  status: "publish",
  featured: false,
  catalog_visibility: "visible",
  description:
    '<div class="section section_01" data-type="bg" data-id="fb2x78hy66">\n<h2 style="text-align: center;"><strong><span class="xm-text header" data-key="" data-type="text" data-id="wh0pgc1o1l">POCO X3 Pro</span></strong></h2>\n<p>&nbsp;</p>\n</div>\n<div class="section section_16" data-type="bg" data-id="8y9ofs1jvo">\n<div class="content-box">\n<p>POCO X3 Pro<br />\nExactamente lo que necesita y más<br />\nSnapdragon ™ 860 | Pantalla de puntos de 120 Hz Corning® Gorilla® Glass 6</p>\n<h2>¡TODO LO QUE AMASTE DE POCO X3, Y MÁS POCO X3 Pro!</h2>\n<p>Mantenga la pantalla suave como la seda, la batería gigante, la carga ultrarrápida y los altavoces con calidad de estudio.<br />\nActualiza donde importa<br />\nMÁS<br />\nACTUACIÓN<br />\nQualcomm® Snapdragon ™ 860 | Almacenamiento UFS 3.1<br />\nDISEÑO<br />\nCorning® Gorilla® Glass 6 | Cuerpo de doble textura<br />\nCREATIVO<br />\nFotografía nocturna mejorada | Vídeo dual</p>\n<h3>RENDIMIENTO A NIVEL DE FLAGSHIP</h3>\n<p>Qualcomm® Snapdragon ™ 860<br />\nPROCESADOR LÍDER 4G EN EL 2021<br />\nEl procesador Qualcomm® Snapdragon ™ 860 no te defraudará incluso cuando juegues juegos con gráficos exigentes en configuraciones altas. Disfruta de altas velocidades y un juego en línea sin demoras.</p>\n<p>71<br />\n%<br />\nMÁS RÁPIDO<br />\nCPU Kryo 485</p>\n<p>145<br />\n%<br />\nMÁS RÁPIDO<br />\nAdreno 640 GPU</p>\n<p>192<br />\n%<br />\nMAS PODEROSO<br />\nMotor de IA</p>\n<p>45<br />\n%<br />\nMÁS ALTO<br />\nPuntuación AnTuTu *<br />\nAlmacenamiento UFS 3.1</p>\n<h3>VELOCIDAD DE ALMACENAMIENTO A NIVEL DE FLAGSHIP POCO X3 Pro</h3>\n<p>Con la tecnología de memoria mejorada UFS 3.1, el POCO X3 Pro ofrece rápidas velocidades de lectura y escritura. Carga juegos y aplicaciones sin tener que esperar.<br />\nUFS 3.1<br />\nUFS 2.1<br />\nTecnología LiquidCool 1.0 Plus</p>\n<h3>MANTÉNGASE FRESCO MIENTRAS JUEGA</h3>\n<p>Mantenga fácilmente el máximo rendimiento durante las sesiones de juego intensas. ¡El calor se disipa en 3D para que pueda seguir jugando a toda velocidad!<br />\nRefrigeración del procesador de hasta 6 ° C<br />\nGrafito multicapa<br />\nTubo de calor de cobre D5<br />\nDISEÑADO PARA ACELERAR<br />\nFrecuencia de actualización de 120 Hz</p>\n<h3>JUEGO SUAVE, DESLIZA SUAVE</h3>\n<p>Con una frecuencia de actualización alta de 120 Hz, nunca perderás el ritmo. Disfruta de movimientos fluidos y fluidos en juegos llenos de acción y mantente por delante de la competencia.<br />\nFrecuencia de muestreo táctil de 240 Hz<br />\nRESPUESTA RÁPIDA PARA JUEGOS<br />\nLa alta frecuencia de muestreo táctil de 240Hz disminuye la latencia táctil y la pantalla receptiva brinda un mejor control de sensibilidad en el juego, llevando su experiencia de juego al siguiente nivel.<br />\nCorning® Gorilla® Glass 6<br />\nPROTECCIÓN DE PANTALLA DE FLAGSHIP<br />\nRendimiento de caída mejorado<br />\nSobrevive a caídas de hasta 1,6 m sobre superficies duras y rugosas.<br />\nRendimiento mejorado de scratch<br />\nMejora hasta 2x en comparación con aluminosilicato alternativo *.</p>\n<p>Diseño de doble textura<br />\nJUEGO CON ESTILO<br />\nPOCO X3 Pro tiene un aspecto nuevo y mejorado con una tira de croma reflectante en el centro y una textura metálica en los lados. Con un material mejorado resistente a las huellas dactilares, su teléfono siempre se verá como nuevo.</p>\n<p>SIEMPRE ENCENDIDO<br />\nBatería de 5160mAh<br />\nJUEGO POR HORAS</p>\n<p>11<br />\nHORAS<br />\nde juegos</p>\n<p>18<br />\nHORAS<br />\nde videos</p>\n<p>110<br />\nHORAS<br />\nde musica*<br />\nCarga rápida de 33 W</p>\n<h3>NO HAY NECESIDAD DE ESPERAR</h3>\n<p>Con una carga rápida de 33 W, el POCO X3 Pro se enciende rápidamente, asegurándose de que siempre esté listo para comenzar. ¡No dejes que la carga lenta te detenga!<br />\n30<br />\nmin<br />\ncobrar al 59%<br />\n59<br />\nmin<br />\ncargar al 100%<br />\nESTAR COMPLETAMENTE SUMERGIDO<br />\nMotor lineal del eje Z<br />\nSIENTE CADA ACCIÓN<br />\nEl motor lineal del eje Z proporciona la respuesta de vibración más vívida. Cada interacción entre la yema del dedo y la pantalla se verá recompensada con una respuesta de vibración delicada e inteligente.<br />\nAltavoces duales<br />\nEXPERIENCIA DE SONIDO ENVOLVENTE<br />\nEscuche los alrededores del juego como si estuviera dentro de la pantalla. Los altavoces duales ofrecen un potente sonido con calidad de estudio, ya sea que esté jugando o escuchando música ,ademas del increible y potente sonido que ofrece el dispositivo.</p>\n<h3>LISTO PARA DISPARAR</h3>\n<p>Cámara cuádruple AI<br />\nCÁMARA QUAD PARA 4X LA DIVERSIÓN<br />\n48MP<br />\ncámara principal<br />\n8MP<br />\ncámara ultra gran angular<br />\n2MP<br />\nsensor de profundidad<br />\n2MP<br />\ncámara macro<br />\nCámara cuádruple AI<br />\nCAPTURA CERCA Y LEJOS</p>\n<p>Vídeo dual<br />\nSEA CREATIVO CON PERSPECTIVAS DUALES<br />\nGrabe simultáneamente con la cámara frontal y trasera para grabar videos emocionantes e innovadores.<br />\nModo nocturno</p>\n</div>\n</div>\n<p>&nbsp;</p>\n<div class="section section_16" data-type="bg" data-id="8y9ofs1jvo">\n<h3 class="content-box">CELULAR POCO X3 PRO EXPLORA MÁS CON FOTOGRAFÍA NOCTURNA</h3>\n<div class="content-box">\n<p>&nbsp;</p>\n<p>Fotos nocturnas más amplias<br />\nHorizontes de la ciudad y cielos estrellados: impresionantes tomas de gran angular en la oscuridad<br />\nSelfies nocturnas<br />\nDisfrute de la iluminación estilo estudio sin importar qué tan oscuro se ponga.</p>\n<p>MÁS FUNCIONES</p>\n<p>NFC *</p>\n<p>IR Blaster</p>\n<p>IP53</p>\n<p>3,5 mm<br />\ntoma de auriculares</p>\n<p>&nbsp;</p>\n<p>Encuentra mas de la familia Poco:<a href="http://www.tugangastores.com/tienda/celularestablets-y-acessorios/celulares/xiaomi/xiaomi-poco-m3/">Poco M3</a> , <a href="http://www.tugangastores.com/tienda/celularestablets-y-acessorios/celulares/xiaomi/xiaomi-poco-x3-nfc/">Poco X3 NFC</a>,  <a href="http://www.tugangastores.com/tienda/celularestablets-y-acessorios/celulares/xiaomi/poco-f3/" rel="nofollow">POCO F3</a></p>\n<p>&nbsp;</p>\n</div>\n</div>\n',
  short_description:
    '<p>ESPECIFICACIONES</p>\n<div class="section section_01" data-type="bg" data-id="fb2x78hy66">\n<div class="module-title"><span class="xm-text tit f36 f-bold" data-key="spec_4" data-type="text" data-id="z0gq0iyotl">Almacenamiento y RAM</span></div>\n<div class="content-box"><span class="xm-text sub-tit f30 f-bold" data-key="spec_5" data-type="text" data-id="8itz6dzhsp">6 + 128 GB / 8 + 256 GB</span><span class="xm-text desc f22 f-regular" data-key="spec_6" data-type="text" data-id="070rbqgodl">LPDDR4X + UFS 3.1</span><span class="xm-text note f18 f-light" data-key="spec_7" data-type="text" data-id="1leal3z2ju">* El almacenamiento y la RAM disponibles son menores que la memoria total debido al almacenamiento del sistema operativo y el software preinstalado en el dispositivo. * Las configuraciones disponibles varían según las regiones.</span></div>\n</div>\n<div class="section section_02" data-type="bg" data-id="iwwzqukri3">\n<div class="module-title"><span class="xm-text tit f36 f-bold" data-key="spec_8" data-type="text" data-id="bf0d7i00m7">Dimensiones</span></div>\n<div class="content-box"><span class="xm-text desc f22 f-regular" data-key="spec_9" data-type="text" data-id="clk6dtcgn7">Altura: 165,3 mm</span><span class="xm-text desc f22 f-regular" data-key="spec_10" data-type="text" data-id="hgucqeu4a0">Ancho: 76,8 mm</span><span class="xm-text desc f22 f-regular" data-key="spec_11" data-type="text" data-id="fwib5z10fh">Espesor: 9,4 mm</span><span class="xm-text desc f22 f-regular" data-key="spec_12" data-type="text" data-id="59wxahq98h">Peso: 215g</span><span class="xm-text note f18 f-light" data-key="spec_13" data-type="text" data-id="4mybzs2a1d">* Datos proporcionados por laboratorios internos. Los métodos de medición de la industria pueden variar y, por lo tanto, los resultados reales pueden diferir.</span></div>\n</div>\n<div class="section section_03" data-type="bg" data-id="gemoh4db8d">\n<div class="module-title"></div>\n</div>\n',
  sku: "119854673",
  price: "",
  regular_price: "",
  sale_price: "",
  date_on_sale_from: null,
  date_on_sale_from_gmt: null,
  date_on_sale_to: null,
  date_on_sale_to_gmt: null,
  on_sale: false,
  purchasable: false,
  total_sales: 14,
  virtual: false,
  downloadable: false,
  downloads: [],
  download_limit: -1,
  download_expiry: -1,
  external_url: "",
  button_text: "",
  tax_status: "taxable",
  tax_class: "",
  manage_stock: false,
  stock_quantity: null,
  backorders: "no",
  backorders_allowed: false,
  backordered: false,
  low_stock_amount: null,
  sold_individually: false,
  weight: "",
  dimensions: {
    length: "",
    width: "",
    height: "",
  },
  shipping_required: true,
  shipping_taxable: true,
  shipping_class: "",
  shipping_class_id: 0,
  reviews_allowed: true,
  average_rating: "5",
  rating_count: 0,
  upsell_ids: [],
  cross_sell_ids: [],
  parent_id: 0,
  purchase_note: "",
  categories: [
    {
      id: 21,
      name: "Categorias",
      slug: "categorias",
    },
    {
      id: 25,
      name: "Celulares",
      slug: "celulares",
    },
    {
      id: 24,
      name: "Celulares,Tablets y Acessorios",
      slug: "celularestablets-y-acessorios",
    },
    {
      id: 27,
      name: "Xiaomi",
      slug: "xiaomi",
    },
  ],
  tags: [],
  images: [
    {
      id: 5179,
      date_created: "2021-07-21T09:56:06",
      date_created_gmt: "2021-07-21T14:56:06",
      date_modified: "2021-07-21T09:56:45",
      date_modified_gmt: "2021-07-21T14:56:45",
      src: "https://www.tugangastores.com/wp-content/uploads/2021/06/poco-x3-pro-1.jpg",
      name: "poco x3 pro",
      alt: "POCO X3 Pro",
    },
    {
      id: 5178,
      date_created: "2021-07-21T09:55:54",
      date_created_gmt: "2021-07-21T14:55:54",
      date_modified: "2021-07-21T09:56:42",
      date_modified_gmt: "2021-07-21T14:56:42",
      src: "https://www.tugangastores.com/wp-content/uploads/2021/06/POCO-X3-Pro-4-1.jpg",
      name: "POCO X3 Pro 4",
      alt: "POCO X3 Pro",
    },
    {
      id: 5177,
      date_created: "2021-07-21T09:55:43",
      date_created_gmt: "2021-07-21T14:55:43",
      date_modified: "2021-07-21T09:56:41",
      date_modified_gmt: "2021-07-21T14:56:41",
      src: "https://www.tugangastores.com/wp-content/uploads/2021/06/POCO-X3-Pro-3-1.jpg",
      name: "POCO X3 Pro 3",
      alt: "POCO X3 Pro",
    },
    {
      id: 5176,
      date_created: "2021-07-21T09:55:31",
      date_created_gmt: "2021-07-21T14:55:31",
      date_modified: "2021-07-21T09:56:39",
      date_modified_gmt: "2021-07-21T14:56:39",
      src: "https://www.tugangastores.com/wp-content/uploads/2021/06/POCO-X3-Pro-2-1.jpg",
      name: "POCO X3 Pro 2",
      alt: "POCO X3 Pro",
    },
  ],
  attributes: [
    {
      id: 1,
      name: "capacidad",
      position: 0,
      visible: true,
      variation: true,
      options: ["128GB", "256GB"],
    },
    {
      id: 2,
      name: "Color",
      position: 1,
      visible: true,
      variation: false,
      options: ["plateado", "rojo", "verde"]
    },
  ],
  default_attributes: [],
  variations: [5572, 5573, 5574, 5575, 5576, 5577],
  grouped_products: [],
  menu_order: 0,
  price_html: "",
  related_ids: [2610, 5383, 2049, 4786, 5407],
  meta_data: [
    {
      id: 23180,
      key: "rank_math_internal_links_processed",
      value: "1",
    },
    {
      id: 23197,
      key: "neve_meta_enable_content_width",
      value: "off",
    },
    {
      id: 23201,
      key: "_yoast_wpseo_focuskw",
      value: "POCO X3 Pro",
    },
    {
      id: 23202,
      key: "_yoast_wpseo_title",
      value:
        "%%title%% 128GB/256GB 144HZ%%page%% %%sep%% %%sitename%% Tienda Virtual",
    },
    {
      id: 23203,
      key: "_yoast_wpseo_metadesc",
      value:
        "POCO X3 Pro , ¡TODO LO QUE AMASTE DE POCO X3, Y MÁS!Mantenga la pantalla suave como la seda, la batería gigante y la carga ultrarrápida",
    },
    {
      id: 23204,
      key: "_yoast_wpseo_linkdex",
      value: "78",
    },
    {
      id: 23205,
      key: "_yoast_wpseo_content_score",
      value: "90",
    },
    {
      id: 23206,
      key: "_yoast_wpseo_estimated-reading-time-minutes",
      value: "4",
    },
    {
      id: 23207,
      key: "_yoast_wpseo_primary_product_cat",
      value: "34",
    },
    {
      id: 23208,
      key: "rank_math_primary_product_cat",
      value: "34",
    },
    {
      id: 23209,
      key: "rank_math_title",
      value: "%title% 128GB/256GB %page% %sep% %sitename% Tienda Online",
    },
    {
      id: 23210,
      key: "rank_math_description",
      value:
        "POCO X3 Pro , ¡TODO LO QUE AMASTE DE POCO X3, Y MÁS!Mantenga la pantalla suave como la seda, la batería gigante y la carga ultrarrápida",
    },
    {
      id: 23211,
      key: "rank_math_focus_keyword",
      value: "POCO X3 Pro,celular poco x3 pro",
    },
    {
      id: 23212,
      key: "rank_math_news_sitemap_robots",
      value: "index",
    },
    {
      id: 23213,
      key: "rank_math_robots",
      value: ["index"],
    },
    {
      id: 23214,
      key: "rank_math_analytic_object_id",
      value: "6",
    },
    {
      id: 23215,
      key: "rank_math_internal_links_processed",
      value: "1",
    },
    {
      id: 23216,
      key: "rank_math_permalink",
      value: "poco-x3-pro",
    },
    {
      id: 23217,
      key: "rank_math_seo_score",
      value: "77",
    },
    {
      id: 23218,
      key: "rank_math_advanced_robots",
      value: {
        "max-snippet": "-1",
        "max-video-preview": "-1",
        "max-image-preview": "large",
      },
    },
    {
      id: 23219,
      key: "rank_math_facebook_enable_image_overlay",
      value: "off",
    },
    {
      id: 23220,
      key: "rank_math_facebook_image_overlay",
      value: "play",
    },
    {
      id: 23221,
      key: "rank_math_twitter_use_facebook",
      value: "on",
    },
    {
      id: 23222,
      key: "rank_math_twitter_card_type",
      value: "summary_large_image",
    },
    {
      id: 23223,
      key: "rank_math_twitter_enable_image_overlay",
      value: "off",
    },
    {
      id: 23224,
      key: "rank_math_twitter_image_overlay",
      value: "play",
    },
    {
      id: 27744,
      key: "_product_feed_status_main-product-catalog",
      value: "SAVED",
    },
    {
      id: 28999,
      key: "fb_product_group_id",
      value: "4739123669443275",
    },
    {
      id: 29111,
      key: "rank_math_contentai_score",
      value: {
        wordCount: "100",
        linkCount: "0",
        headingCount: "100",
        mediaCount: "62.22",
        keywords: "74.51",
      },
    },
    {
      id: 29112,
      key: "_wc_facebook_commerce_enabled",
      value: "no",
    },
    {
      id: 29113,
      key: "neve_meta_content_width",
      value: "70",
    },
    {
      id: 29114,
      key: "rank_math_primary_fb_product_set",
      value: "0",
    },
  ],
  stock_status: "instock",
  _links: {
    self: [
      {
        href: "https://www.tugangastores.com/wp-json/wc/v3/products/4673",
      },
    ],
    collection: [
      {
        href: "https://www.tugangastores.com/wp-json/wc/v3/products",
      },
    ],
  },
};
