export const types = {
    ADD_QUANTITY:"ADD_QUANTITY",
    LESS_QUANTITY:"LESS_QUANTITY",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_OF_CART:"REMOVE_OF_CART",
    REMOVE_ONE_PRODUCT:"REMOVE_ONE_PRODUCT",
    REMOVE_ALL_CART:"REMOVE_ALL_CART",
    TOTAL_CART:"TOTAL_CART"
}