const types = {
  PRODUCT_ACTIVE: "PRODUCT_ACTIVE",
  VARIATION_ACTIVE: "VARIATION_ACTIVE",
  VARIATIONS: "VARIATIONS",
  SELECT_OPTIONS: "SELECT_OPTIONS",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_QUANTITY:"ADD_QUANTITY",
  LESS_QUANTITY:"LESS_QUANTITY"
};

export default types;
